name: Hugo Deploy

on: 
  push:
    branches:
      - main

jobs:
  hugo:
    uses: diegotony/gh-pipelines/.github/workflows/hugo-custom-domain.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      CUSTOM_DOMAIN: blog.constant1n396.com
